image: gradle:7.6-jdk17-alpine

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

before_script:
  - chmod u+x ./gradlew

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - ./gradlew wrapper assemble
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  script:
    - ./gradlew clean test
  artifacts:
    reports:
      junit:
        - build/test-results/test/*.xml
      coverage:
        - build/reports/jacoco/test/html/*

deploy:
  stage: deploy
  script:
    - mv build/reports/jacoco/test/html public/
  artifacts:
    paths:
      - public/*
  only:
    - master
  when: manual
