#
# Copyright Andret (c) 2018-2023. Copying and modifying allowed only keeping git link reference.
#
image: gradle:8-jdk17-alpine

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - ~/.gradle/caches

before_script:
  - chmod +x gradlew

stages:
  - build
  - test
  - deploy

compile:
  stage: build
  script:
    - ./gradlew wrapper assemble
  artifacts:
    paths:
      - build/libs/*.jar

junit:
  stage: test
  dependencies:
    - compile
  script:
    - ./gradlew clean test
  coverage: '/    - Instruction Coverage: ([0-9.]+)%/'
  artifacts:
    reports:
      junit:
        - build/test-results/test/*.xml
    paths:
      - build/reports/jacoco/test/html/**

pages:
  image: nginx:alpine
  stage: deploy
  dependencies:
    - junit
  script:
    - mv build/reports/jacoco/test/html/ public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual
