image: gradle:7.5-jdk17

before_script:
  - chmod u+x ./gradlew

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - ./gradlew wrapper assemble
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  script:
    - ./gradlew clean test --scan
  artifacts:
    reports:
      junit:
        - build/test-results/test/*.xml

deploy:
  stage: deploy
  script:
    - mv build/reports/jacoco/test/html public/
  artifacts:
    paths:
      - public/*
  only:
    - master
  when: manual
