plugins {
	id 'org.jetbrains.intellij' version '1.8.0'
}

apply plugin: 'java'
apply plugin: 'idea'

sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

// See https://github.com/JetBrains/gradle-intellij-plugin/
intellij {
	version = '2022.2'
	plugins = ['com.intellij.java']
	updateSinceUntilBuild = false
}

buildSearchableOptions {
	enabled = false
}

patchPluginXml {
	version = project.version
	setSinceBuild '193'
}

group project.group
version project.version

repositories {
	mavenCentral()
}

dependencies {
	compileOnly group: 'org.projectlombok', name: 'lombok', version: '1.18.24'
	annotationProcessor group: 'org.projectlombok', name: 'lombok', version: '1.18.24'
}

jar {
	from {
		configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
	}
}
