plugins {
	id 'org.jetbrains.intellij' version '1.1.4'
}

apply plugin: 'java'
apply plugin: 'idea'

sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

// See https://github.com/JetBrains/gradle-intellij-plugin/
intellij {
	version = '2021.2.1'
	plugins = ['com.intellij.java']
}

buildSearchableOptions {
	enabled = false
}

patchPluginXml {
	version = project.version
	sinceBuild = '202'
}

group project.group
version project.version

repositories {
	mavenCentral()
	maven { url 'https://gitlab.com/api/v4/groups/2877017/-/packages/maven' }
}

dependencies {
	compileOnly group: 'org.projectlombok', name: 'lombok', version: '1.18.20'
	implementation group: 'eu.andret', name: 'ats-arguments', version: project.argumentsVersion
	annotationProcessor group: 'org.projectlombok', name: 'lombok', version: '1.18.20'

	testCompileOnly group: 'org.projectlombok', name: 'lombok', version: '1.18.20'
	testAnnotationProcessor group: 'org.projectlombok', name: 'lombok', version: '1.18.20'
}

jar {
	from {
		configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
	}
}

println "PUBLISH_TOKEN = " + System.getenv("PUBLISH_TOKEN")
println "CERTIFICATE_CHAIN = " + System.getenv("CERTIFICATE_CHAIN")
println "PRIVATE_KEY = " + System.getenv("PRIVATE_KEY")
println "PRIVATE_KEY_PASSWORD = " + System.getenv("PRIVATE_KEY_PASSWORD")
println System.getenv()

publishPlugin {
	channels = ['alpha']
	token = System.getenv("PUBLISH_TOKEN")
}

signPlugin {
	certificateChain = System.getenv("CERTIFICATE_CHAIN")
	privateKey = System.getenv("PRIVATE_KEY")
	password = System.getenv("PRIVATE_KEY_PASSWORD")
}
